### PR TITLE
collate and upload test statistics for melodic devel jobs on bionic

### PR DESCRIPTION
**Pull request by dirk-thomas**
See ros-infrastructure/ros_buildfarm#541.

### CODE REVIEW

**Comment by clalancette** [comment]
Can we hold off on deploying this until May 11th?  While I'm all for trying this out on Melodic, I'd like to get the Melodic beta out before we make new changes to the buildfarm.

**Comment by dirk-thomas** [comment]
This doesn't affect any of the source / binary jobs. And in the case that it break any of the dev jobs we can easily disable the feature again. I also doesn't result in any extra builds to be run so I don't see a strong reason to hold back on it.

**Review by tfoote — APPROVED** [review]
I think this is low risk of effecting the melodic sync, but holding off for 2 day also isn't too much.

**Comment by dirk-thomas** [comment]
Ok, I will leave it up to @clalancette thento merge this when he is ready.

**Comment by gavanderhoorn** [comment]
Thanks :+1:

**Pull request merged**
