### PR TITLE
blacklist rqt_multiplot (missing librqt-qt5-dev)

### PR DESCRIPTION
**Pull request by samuelba**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Please add the new entries in alphabetical order. That will help browsing the lists once they get bigger. Thanks.

**Comment by samuelba** [comment]
sorry, fixed

**Comment by dirk-thomas** [comment]
Np, not documented anywhere :wink: Thanks for the fast update.

**Comment by dirk-thomas** [comment]
The Jessie job was disabled last night based on this PR.

I just reenabled it to check that the new auto-disable feature for sourcedeb jobs works as intended which disables repeatedly failing sourcedeb jobs (see ros-infrastructure/ros_buildfarm315). And your job was the perfect one to try it with :wink:. So you have likely received one more notification for this build: http://build.ros.org/view/Ksrc_dJ/job/Ksrc_dJ__rqt_multiplot__debian_jessie__source/332/

**Pull request merged**
