### PR TITLE
up indigo sync level in production

### PR DESCRIPTION
**Pull request by tfoote**
Matches #11

### CODE REVIEW

**Comment by dirk-thomas** [comment]
lgtm.

**Comment by dirk-thomas** [comment]
Since this has been merged Indigo was never able to sync on Saucy since it is almost 40 packages short.

**Comment by tfoote** [comment]
yes, there's a noteable regression on saucy, which is what this is designed to protect against. the ecl packages were requiring a too new version of cmake for saucy.

**Comment by dirk-thomas** [comment]
Is upstream working on this and we are waiting for a working build or will we not sync Saucy anymore before removing it from the build farm?

**Comment by dirk-thomas** [comment]
Is upstream working on this and we are waiting for a working build or will we not sync Saucy anymore before removing it from the build farm?

**Pull request merged**
