### PR TITLE
Remove visp from blacklist

### PR DESCRIPTION
**Pull request by fspindle**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
To affect the official ROS build farm the patch needs to be applied to the `production` branch.

**Comment by dirk-thomas** [comment]
After this has been merged the build farm will update itself automatically in the next 24h.

**Comment by tfoote** [comment]
This was blacklisted because it was not building in #7 

It looks to me like it was failing because of a missing dependency: https://groups.google.com/forum/#!searchin/ros-buildfarm-indigo/failed$20visp%7Csort:date/ros-buildfarm-indigo/Wu2ngACH5FE/P9usHxrqEgAJ

Can you point to a change as to why to expect it will start building again if we unblacklist it? I don't see a change in the status of libsoqt4-dev being available on arm http://packages.ubuntu.com/trusty/libsoqt4-dev http://packages.ubuntu.com/wily/libsoqt4-dev

**Comment by fspindle** [comment]
I haven't seen that yet. I will close this PR to make a fresh one in production branch and then release again visp for indigo and jade without libsoqt4-dev dependency

**Pull request closed without merging**
