### PR TITLE
unblacklist librealsense

### PR DESCRIPTION
**Pull request by jackieokay**
@mdhorn

### CODE REVIEW

**Comment by tfoote** [comment]
Note this needs a new librealsense release before this will work: https://github.com/ros/rosdistro/pull/12036#issuecomment-231804462

I see you released into indigo (https://github.com/ros/rosdistro/pull/12123)  and that's working now on armhf.
http://build.ros.org/job/Ibin_arm_uThf__librealsense__ubuntu_trusty_armhf__binary/

You'll also need to rerun bloom for kinetic for the above to blacklist to change anything.

**Comment by mdhorn** [comment]
@jacquelinekay @tfoote My bad, I only rereleased indigo. Just submitted the Kinetic.
https://github.com/ros/rosdistro/pull/12130

**Comment by tfoote** [comment]
merged to let the new jobs build

**Comment by mdhorn** [comment]
I'm seeing Kinetic jobs failing include the targets which were passing before.
The error 'Failed to fetchInvocation failed due to the following known error conditions: , Hash Sum mismatch'
Is this due to the code having a new hash for the same release number?

**Comment by tfoote** [comment]
Yeah, it is not proper debian practice to change the orig.tar.gz files. With the changed upstream tag this is caused. There's an enhancement request to bloom to work around this as a debian maintainer would but it's uncommon enough that we haven't prioritized it and generally strongly recommend not changing tags. https://github.com/ros-infrastructure/bloom/issues/150

This is in combination with our build machines caching content and I think the reprepro repo does not set expiration headers correctly for the orig.tar.gz so it ends up with the old one. 

I've forced the builds onto a different executor which should avoid the cache. It looks like one of the builds has passed I'll retrigger the other.

**Comment by mdhorn** [comment]
@tfoote Are the ARM builds run on ARM hardware? Or do you have ARM docker images that run on x86 servers?
I was really surprised to see that the 64-bit ARM build failed not liking the flags that were passed. I'm not an ARM expert, but the options listed appear to be valid to be based on https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html.

I need to figure out a method to test the ARM options besides pushing them through the ROS build farm for the first time.

**Comment by tfoote** [comment]
We're running arm builds inside docker with QEMU emulation. It does appear that they're having trouble with the flags on arm64/aarch64. 

The flags failing in http://build.ros.org/job/Kbin_djv8_dJv8__librealsense__debian_jessie_arm64__binary/11/console 

```
15:10:25 g++ src/uvc-libuvc.cpp -std=c++11 -fPIC -pedantic -Ofast -Wno-missing-field-initializers -Wno-switch -Wno-multichar -DRS_USE_V4L2_BACKEND `pkg-config --cflags --libs libusb-1.0` -mfpu=neon -mfloat-abi=hard -ftree-vectorize -c -o obj/uvc-libuvc.o
15:10:25 g++: error: unrecognized command line option ‘-mfpu=neon’
15:10:25 g++: error: unrecognized command line option ‘-mfloat-abi=hard’
```

I think for the arm64 builds the relevant gcc options available are here: https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html#AArch64-Options

They don't appear to inherit the generic ARM options. 

If you have docker and qemu-user-static installed you should be able run 
`$ docker run -ti --rm osrf/debian_arm64:jessie bash` to get an environment
`apt-get update && apt-get install -y g++` will get you g++ in the same environment. 
Using that I can reproduce the errors with a trivial int main return program. 

```
root@f5a43b8183e2:/# g++ -mfpu=neon -mfloat-abi=hard test.cpp 
g++: error: unrecognized command line option '-mfpu=neon'
g++: error: unrecognized command line option '-mfloat-abi=hard'
```

But it will take the aarch64 options. 

```
root@8a4c3563cfca:/# g++ -mstrict-align test.cpp 
root@8a4c3563cfca:/# ./a.out 
```

**Comment by mdhorn** [comment]
Okay, I had tried getting the docker image working for ARM over the weekend and missed the qemu-user-static part.

Just built a osrf/debian_arm64:jessie image, installed ROS and build librealsense okay using this delta:

> -CXXFLAGS += -mfpu=neon -mfloat-abi=hard -ftree-vectorize
> +CXXFLAGS += -mstrict-align -ftree-vectorize

I'm submitting a librealsense PR and once it is updated (hopefully over night), I'll run bloom tomorrow.

**Comment by mdhorn** [comment]
The changes were merged into the librealsense code base and I submitted new PRs for releasing librealsense for both Indigo and Kinetic. Looks like now builds for all platforms.
I'll rerun bloom-release for realsense_camera to ensure that package is now built for all platforms.

**Pull request merged**
