### PR TITLE
Reenable debian jobs

### PR DESCRIPTION
**Pull request by mikaelarguedas**
to be merged once the catkin debian job is green

### CODE REVIEW

**Review by tfoote — APPROVED** [review]
It's green now: http://build.ros.org:8080/view/Lsrc_dS/job/Lsrc_dS__catkin__debian_stretch__source/

**Comment by dirk-thomas** [comment]
This is still blocked on ros-infrastructure/buildfarm_deployment#145

**Comment by mikaelarguedas** [comment]
@dirk-thomas do you prefer testing https://github.com/ros-infrastructure/ros_buildfarm/issues/387 before merging this?

**Comment by dirk-thomas** [comment]
Let's first merge this, see that they all run (maybe fail due to `apt-src`) and then deploy the `apt-src` workaround to see if all jobs pass on a rebuild.

**Comment by mikaelarguedas** [comment]
Sounds good

**Pull request merged**
