### PR TITLE
Disable EOL Ubuntu distros

### PR DESCRIPTION
**Pull request by dirk-thomas**
This patch comments out all EOLed Ubuntu distros.

### CODE REVIEW

**Review by tfoote — APPROVED** [review]

**Comment by dirk-thomas** [comment]
The corresponding Groovy script:

```
count = 0
Jenkins.instance.getAllItems(AbstractProject.class).each {it ->
  if (
    it.fullName.startsWith("Isrc_uS_") ||
    it.fullName.startsWith("Ibin_uS32_") ||
    it.fullName.startsWith("Ibin_uS64_") ||
    it.fullName.endsWith("_saucy_amd64") ||
    it.fullName.endsWith("_saucy_i386") ||
    it.fullName.startsWith("Jsrc_uU_") ||
    it.fullName.startsWith("Jbin_uU32_") ||
    it.fullName.startsWith("Jbin_uU64_") ||
    it.fullName.endsWith("_utopic_amd64") ||
    it.fullName.endsWith("_utopic_i386") ||
    it.fullName.startsWith("Jsrc_uV_") ||
    it.fullName.startsWith("Jbin_uV32_") ||
    it.fullName.startsWith("Jbin_uV64_") ||
    it.fullName.endsWith("_vivid_amd64") ||
    it.fullName.endsWith("_vivid_i386") ||
    it.fullName.startsWith("Ksrc_uW_") ||
    it.fullName.startsWith("Kbin_uW32_") ||
    it.fullName.startsWith("Kbin_uW64_") ||
    it.fullName.endsWith("_wily_amd64") ||
    it.fullName.endsWith("_wily_i386")
  ) {
    println it.fullName;
    count += 1
    
    if (it.isBuildable()) {
      it.disable()
    }
  }
}
println ""
println count  // affects 18353 jobs
```

**Comment by dhood** [comment]
We should change the wording on the binary install instructions to remove EOL distros, right? eg "ROS Indigo ONLY supports Saucy (13.10) and Trusty (14.04) for debian packages." -> "ROS Indigo ONLY supports Trusty (14.04) for debian packages." If so I'll go ahead and update them.

**Comment by mikaelarguedas** [comment]
all the binaries available for the EOL platforms were valid at the time of the build. People can still install them and last time they were built they passed all tests. I agree we can rephrase but there are still binaries that were tested for these distributions so I'm not sure we should remove them completely

**Comment by dhood** [comment]
OK nothing is broken for users atm. I thought EOL users wouldn't be able to install anything at all. well maybe being an EOL distro implies that their packages will be out of date? not sure what the standard practice is there.

**Comment by tfoote** [comment]
The goal is not to break things for users on EOL platforms. Being EOL just means that they don't get updates. But existing EOL distro users can install the last versions available of whatever was available at the time of EOL.

I would keep the current wording but state "Saucy is EOL as of XYZ and won't get any updates."

**Pull request merged**
