### PR TITLE
[melodic] blacklist mapviz on armhf

### PR DESCRIPTION
**Pull request by pjreed**
It doesn't build and there are no plans to fix it.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@pjreed it looks like if failed on [armv8](http://build.ros.org/view/Mbin_ubv8_uBv8/job/Mbin_ubv8_uBv8__mapviz__ubuntu_bionic_arm64__binary/2/consoleFull) (same error as [armhf](http://build.ros.org/view/Mbin_ubhf_uBhf/job/Mbin_ubhf_uBhf__mapviz__ubuntu_bionic_armhf__binary/2/consoleFull)) as well on bionic but passed on Debian.
This suggests a dependency issue on bionic. Would you mind double checking if this can be fixed on armv8 or if it need to be blacklisted there as well?

Thanks!

**Comment by pjreed** [comment]
Just noticed that this was still open...

Anyway, I don't think it's a dependency issue. The build is failing because the OpenGL API on armv8 / Ubuntu is missing functions that it needs, but I guess those must exist on armv8 / Debian.  I'm not sure if there's a way to fix that.

**Comment by clalancette** [comment]
To be clear, it is not missing any functions.  It is that two different headers seem to have two different signatures for the APIs, i.e.:

```
In file included from /usr/include/aarch64-linux-gnu/qt5/QtGui/qopengl.h:105:0,
                 from /usr/include/aarch64-linux-gnu/qt5/QtOpenGL/qgl.h:45,
                 from /usr/include/aarch64-linux-gnu/qt5/QtOpenGL/QGLWidget:1,
                 from /tmp/binarydeb/ros-melodic-mapviz-0.2.6/include/mapviz/map_canvas.h:42,
                 from /tmp/binarydeb/ros-melodic-mapviz-0.2.6/src/map_canvas.cpp:35:
/usr/include/GLES3/gl31.h:1520:88: error: ‘void __glewVertexBindingDivisor(GLuint, GLuint)’ redeclared as different kind of symbol
 GL_APICALL void GL_APIENTRY glVertexBindingDivisor (GLuint bindingindex, GLuint divisor);
                                                                                        ^
In file included from /tmp/binarydeb/ros-melodic-mapviz-0.2.6/src/map_canvas.cpp:31:0:
/usr/include/GL/glew.h:17834:47: note: previous declaration ‘void (* __glewVertexBindingDivisor)(GLuint, GLuint)’
 GLEW_FUN_EXPORT PFNGLVERTEXBINDINGDIVISORPROC __glewVertexBindingDivisor;
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

It bears some investigation, because it may be possible to make this work or workaround the problem.

**Comment by dirk-thomas** [comment]
What is the status of this? If there is no progress I suggest to merge this since currently the jobs are failing once every day.

**Comment by pjreed** [comment]
I haven't looked into it, so unless somebody else wants to work on it, I'd recommend merging it.

**Pull request merged**
