### PR TITLE
internationalize the docs upload and canonical url

### PR DESCRIPTION
**Pull request by tfoote**
This must be merged in conjunction with the server crossover

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Since EOL distros aren't being regenerated why update those entries? I assume the old URLs will be redirected to the new layout anyway (and maybe existing canonical URLs replaced with the new)?

**Comment by tfoote** [comment]
I updated them all because if they're not deleted they are presumably being kept to be potentially turned on again by us in the future or by someone else. This will make it consistent and able to be turned back on. If we don't want to maintain them we should probably just remove them entirely.

There will be redirects for all the legacy urls.

**Review by nuclearsandwich — APPROVED** [review]
Looks good. Shouldn't be merged until the server operation has been performed.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/migration-of-docs-ros-org-content-into-en-prefix/16829/1

**Comment by tfoote** [comment]
Move completed, and backwards compatibility symlinks are installed.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/migration-of-docs-ros-org-content-into-en-prefix/16829/2

**Comment by tfoote** [comment]
They successfully reconfigured overnight: 

- http://build.ros.org/job/Kdoc_reconfigure-jobs/1005/
- http://build.ros.org/job/Mdoc_reconfigure-jobs/719/
- http://build.ros.org/job/Ndoc_reconfigure-jobs/534/

And successfully uploaded with the new directory structure and canonical url generated: http://build.ros.org/view/Kdoc/job/Kdoc__geometry2__ubuntu_xenial_amd64/3

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2020-10-15/16849/1

**Pull request merged**
