### PR TITLE
add debian/jessie/armhf

### PR DESCRIPTION
**Pull request by k-okada**
for raspberrypi type 3B !!
Cc: @furushchev

### CODE REVIEW

**Comment by furushchev** [comment]
@k-okada Thank you for notification.
Could we also add `debian/jessie/armhf` to indigo?

**Comment by tfoote** [comment]
@k-okada thanks for the suggestion. We've done our best to pick the spanning set of target architectures. We have to make a tradeoff between timelyness of builds and costs. We've picked Ubuntu Xenial armhf and Debian Jessie arm64 as a spanning set. Due to emulation these builds cost an order of magnitude more time, which means that building for these 2 architectures takes ~20 times the computation of a single x86 architecture. Adding a third one would put us at 30x which is much bigger than supporting our past 4-8 x86 architectures. As a regular releaser you may have noticed new builds are coming out slower, that's because we've been adding platforms in width. 

It looks like there are Xenial armhf builds which should work linked here: https://wiki.ubuntu.com/ARM/RaspberryPi

@furushchev We cannot add a new target distro to a rosdistro after the fact. I don't have a quick link to that but I know there have been some discussions of that previously on ros-release and or ros-users

**Comment by k-okada** [comment]
@tfoote thanks for explanation, we'll try Xenial on Raspberry PI

**Comment by k-okada** [comment]
@tfoote, Just out of curiosity, how much does it cost for additional building machine for new architecture, for example c4.2xlarge of AWS EC2 would cover them?

**Comment by tfoote** [comment]
Our default build machines are m4.xlarge, We typically run the build farm in steady state with 1-2 machines. During a rebuild we scale up to 8-12. Waiting for the arm builds can take close to a week with that level of executors, while all the x86 architectures can finish in 2-3 days. 

Note I was just saw a demo of a Raspberry Pi 3 based robot running kinetic from debians so it does work. I'm not sure which directions they installed from.

**Comment by tfoote** [comment]
I forgot there is a ticket here which has identified the bottleneck in the arm builds. But there's not a known solution. https://github.com/ros-infrastructure/ros_buildfarm/issues/303

**Pull request closed without merging**
