### PR TITLE
add rqt to Noetic CI

### PR DESCRIPTION
**Pull request by dirk-thomas**
Add the following repos to the Noetic CI builds:
* `python_qt_binding`
* `qt_gui_core`
* `rqt`

CI builds ~(currently failing since `nodelet_core` `actionlib` is missing)~:

* Python 2: [Build Status](http://build.ros.org/view/Nci/job/Nci__bionic-python2_ubuntu_bionic_amd64/26/)
* Python 3: [Build Status](http://build.ros.org/view/Nci/job/Nci__bionic-python3_ubuntu_bionic_amd64/54/)

### CODE REVIEW

**Comment by dirk-thomas** [comment]
With #146 merged I updated this to only add the remaining repo: `rqt`.

**Comment by mjcarroll** [comment]
Rebuilding with actionlib and nodelet_core in:

* Python 2: [Build Status](http://build.ros.org/view/Nci/job/Nci__bionic-python2_ubuntu_bionic_amd64/34/)
* Python 3: [Build Status](http://build.ros.org/view/Nci/job/Nci__bionic-python3_ubuntu_bionic_amd64/63/)

**Comment by mjcarroll** [comment]
Interesting that fails given that it passed over here: https://github.com/ros-infrastructure/ros_buildfarm_config/pull/150

I'm looking into it.

**Comment by dirk-thomas** [comment]
Python 2:
* Without `nodelet_core` and `rqt`: [Build Status](http://build.ros.org/view/Nci/job/Nci__bionic-python2_ubuntu_bionic_amd64/32/) 1 known test failure
* With `nodelet_core` and `rqt`: [Build Status](http://build.ros.org/view/Nci/job/Nci__bionic-python2_ubuntu_bionic_amd64/33/) additionally 1 flaky test in [test_roscpp](http://build.ros.org/view/Nci/job/Nci__bionic-python2_ubuntu_bionic_amd64/33/testReport/(root)/TopicStatisticFrequency/statisticFrequency/) and 1 failing test in [actionlib](http://build.ros.org/view/Nci/job/Nci__bionic-python2_ubuntu_bionic_amd64/33/testReport/rostest.runner/RosTest/testtest_cpp_simple_client/)

Python 3:
* Without `nodelet_core` and `rqt`: [Build Status](http://build.ros.org/view/Nci/job/Nci__bionic-python3_ubuntu_bionic_amd64/62/) 6 known warnings due to PySide2 being unavailable, 4 known test failures
* With `nodelet_core` and `rqt`: [Build Status](http://build.ros.org/view/Nci/job/Nci__bionic-python3_ubuntu_bionic_amd64/61/) failed due to empty result file in `test_nodelet`

**Comment by dirk-thomas** [comment]
Since the Python 3 build without `rqt` already fails due to the empty result files in the `test_nodelet` package (see e.g. [Build Status](http://build.ros.org/view/Nci/job/Nci__bionic-python3_ubuntu_bionic_amd64/65/)) and I don't see anything failing withing `rqt` I am going to merge this PR anyway.

**Pull request merged**
