### PR TITLE
Kinetic blacklists for new layout

### PR DESCRIPTION
**Pull request by jackieokay**
There are new Kinetic build failures because we split out job profiles to be more finely-grained and didn't copy over some blacklists correctly.

I'll tag maintainers here to confirm that blacklisting is appropriate. If you don't think your package should be blacklisted for a particular platform please speak up.

hrpsys: @k-okada @130s
Fails for Xenial armhf, Jessie arm64
http://build.ros.org/job/Kbin_uxhf_uXhf__hrpsys__ubuntu_xenial_armhf__binary/
http://build.ros.org/job/Kbin_djv8_dJv8__hrpsys__debian_jessie_arm64__binary/

mapviz: @evenator
Fails for Xenial armhf
http://build.ros.org/job/Kbin_uxhf_uXhf__mapviz__ubuntu_xenial_armhf__binary/

nerian_sp1: @nerian_vision
Fails for Jessie arm64
http://build.ros.org/job/Kbin_djv8_dJv8__nerian_sp1__debian_jessie_arm64__binary/

schunk_canopen_driver: @fmauch
Fails for Jessie arm64 and amd64
http://build.ros.org/job/Kbin_djv8_dJv8__schunk_canopen_driver__debian_jessie_arm64__binary/

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Nao_meshes missing rosdep key has been updated, I'll rerelease it on Wednesday, no need to blacklist it

**Comment by tfoote** [comment]
couchdb for arm64 has been packaged by linaro and is in their repos. It's been submitted to go upstream, but I can look at importing it to our repos instead of waiting for it.

**Comment by k-okada** [comment]
> hrpsys: @k-okada https://github.com/k-okada @130s
> https://github.com/130s. Fails for Xenial armhf, Jessie arm64

Hi

I'm working on this, will fix this today

On Monday, 27 June 2016, Jackie Kay notifications@github.com wrote:

> There are new Kinetic build failures because we split out job profiles to
> be more finely-grained and didn't copy over some blacklists correctly.
> 
> I'll tag maintainers here to confirm that blacklisting is appropriate. If
> you don't think your package should be blacklisted for a particular
> platform please speak up.
> 
> hrpsys: @k-okada https://github.com/k-okada @130s
> https://github.com/130s
> Fails for Xenial armhf, Jessie arm64
> 
> http://build.ros.org/job/Kbin_uxhf_uXhf__hrpsys__ubuntu_xenial_armhf__binary/
> 
> http://build.ros.org/job/Kbin_djv8_dJv8__hrpsys__debian_jessie_arm64__binary/
> 
> mapviz: @evenator https://github.com/evenator
> Fails for Xenial armhf
> 
> http://build.ros.org/job/Kbin_uxhf_uXhf__mapviz__ubuntu_xenial_armhf__binary/
> 
> object_recognition_[capture, transparent_objects, tod, reconstruction,
> ros]: @vrabaud https://github.com/vrabaud
> Fails for Debian Jessie arm64
> 
> http://build.ros.org/job/Kbin_djv8_dJv8__object_recognition_capture__debian_jessie_arm64__binary/
> 
> http://build.ros.org/job/Kbin_djv8_dJv8__object_recognition_transparent_objects__debian_jessie_arm64__binary/
> 
> http://build.ros.org/job/Kbin_djv8_dJv8__object_recognition_tod__debian_jessie_arm64__binary/
> 
> http://build.ros.org/job/Kbin_djv8_dJv8__object_recognition_reconstruction__debian_jessie_arm64__binary/
> 
> http://build.ros.org/job/Kbin_djv8_dJv8__object_recognition_ros__debian_jessie_arm64__binary/
> 
> nao_meshes: @mikaelarguedas https://github.com/mikaelarguedas
> Fails for Jessie _amd64_
> 
> http://build.ros.org/job/Kbin_dj_dJ64__nao_meshes__debian_jessie_amd64__binary/
> 
> nerian_sp1: @nerian_vision
> Fails for Jessie arm64
> 
> http://build.ros.org/job/Kbin_djv8_dJv8__nerian_sp1__debian_jessie_arm64__binary/
> 
> schunk_canopen_driver: @fmauch https://github.com/fmauch
> Fails for Jessie arm64 and amd64
> 
> ## http://build.ros.org/job/Kbin_djv8_dJv8__schunk_canopen_driver__debian_jessie_arm64__binary/
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/ros-infrastructure/ros_buildfarm_config/pull/50
> Commit Summary
> - Kinetic blacklists for new layout
> - correct name of nerian_sp1
> 
> File Changes
> - _M_ kinetic/release-armhf-build.yaml
>   https://github.com/ros-infrastructure/ros_buildfarm_config/pull/50/files#diff-0
>   (2)
> - _M_ kinetic/release-jessie-arm64-build.yaml
>   https://github.com/ros-infrastructure/ros_buildfarm_config/pull/50/files#diff-1
>   (8)
> - _M_ kinetic/release-jessie-build.yaml
>   https://github.com/ros-infrastructure/ros_buildfarm_config/pull/50/files#diff-2
>   (3)
> 
> Patch Links:
> 
>    -
>    https://github.com/ros-infrastructure/ros_buildfarm_config/pull/50.patch
>    -
>    https://github.com/ros-infrastructure/ros_buildfarm_config/pull/50.diff
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/ros-infrastructure/ros_buildfarm_config/pull/50, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAeG3DQrEe4PH-oMAqJctBl_WHF4X767ks5qP_2wgaJpZM4I_SNq
> .

## 

## 

◉ Kei Okada

**Comment by vrabaud** [comment]
in my case, only object_recognition_core needs to be blacklisted: it run depends on couchdb so nobody can use it anyway. All the other packages you mention should no be built if you blacklist it.

**Comment by tfoote** [comment]
I've added couchdb from the linaro repos to our bootstrap repo: https://github.com/ros-infrastructure/reprepro-updater/blob/master/config/couchdb_debian_jessie_linaro.yaml

**Comment by jackieokay** [comment]
Thanks @tfoote! I've unblacklisted the object_recognition stack. I've also removed nao_meshes from jessie amd64.

**Comment by jackieokay** [comment]
I've also blacklisted librealsense on ARM because the makefile provided by upstream is incompatible with the ARM compiler toolchain.

https://github.com/ros/rosdistro/pull/12036

**Comment by evenator** [comment]
Mapviz should remain blacklisted on ARM due to some OpenGL/Qt issues.

**Comment by jackieokay** [comment]
@tfoote any more feedback about this?

**Comment by tfoote** [comment]
lgtm

**Pull request merged**
