### PR TITLE
disable jade

### PR DESCRIPTION
**Pull request by wjwwood**
Not sure this is the "right" way to do this. I'm open to suggestion.

### CODE REVIEW

**Review by dirk-thomas — APPROVED** [review]
lgtm

**Review by mikaelarguedas — APPROVED** [review]
LGTM, @nuclearsandwich should this be cherry-picked in another branch as well ?

**Comment by nuclearsandwich** [comment]
> LGTM, @nuclearsandwich should this be cherry-picked in another branch as well ?

The production branch is the one build.ros.org is using currently. We could bring this to the example branch (master) though.

**Comment by wjwwood** [comment]
Let me know if there is need for a or to another branch.

**Comment by nuclearsandwich** [comment]
The master branch documentation says "The two branches should be maintained as closely as possible." Since removing jade requires a single 🔪 commit if you could cherry pick this and PR it to master I'd appreciate it.

**Comment by mikaelarguedas** [comment]
On that topic, we discussed a while ago re conciliating the 2 branches once the migration was done successfully and did hold PRs to master in the meantime. Is that still something we plan to do all at once ? or should we start opening individual PRs to get them closer ? (If so I'll make a PR to add lunar to the master branch)

**Comment by nuclearsandwich** [comment]
> Is that still something we plan to do all at once ?

I don't recall being part of a previous conversation but I easily get turned around between the ros_buildfarm_config and the buildfarm_deployment_config in offline conversation.

I think that unless/until we have some scripted method for reconciling these changes it's probably best if we ask PR authors to followup with a master/example PR after the production ones are accepted.

**Comment by wjwwood** [comment]
@nuclearsandwich looks like it is already disabled:

https://github.com/ros-infrastructure/ros_buildfarm_config/blob/f7dbfa52b7b98cf64544ce1bdd5884a836a70b64/index.yaml#L16-L26

**Comment by nuclearsandwich** [comment]
shows what I know then 😁

**Pull request merged**
