### PR TITLE
Changed upload_user to jenkins-agent.

### PR DESCRIPTION
**Pull request by tonybaltovski**
Changed the upload_user to match the job [here](https://github.com/ros-infrastructure/ros_buildfarm/blob/893c10ab3ebee46a1ebb3e9d938349ed67d4d573/ros_buildfarm/config/doc_build_file.py#L140).

### CODE REVIEW

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
Should we consider consider dropping these configuration values in order to let the defaults from source take precedence?

We could keep this change with commented out fields to document the current default state and that it's tuneable.

**Comment by dirk-thomas** [comment]
> Should we consider consider dropping these configuration values in order to let the defaults from source take precedence?
> We could keep this change with commented out fields to document the current default state and that it's tuneable.

Sounds good to me.

**Comment by tonybaltovski** [comment]
Works for me.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
Thanks for the quick turnaround @tonybaltovski 

I don't know that I'll have a chance to test this before the end of the week, but I'm happy to merge it if it's working for you @tonybaltovski I wouldp propose merging it anyway.

**Review by tfoote — APPROVED** [review]

**Comment by tonybaltovski** [comment]
@nuclearsandwich, no rush on merging.

**Comment by nuclearsandwich** [comment]
@dirk-thomas I think we can merge this now but I want to confirm with you.

It targets the example "master" config rather than production and I think it actually improves compatibility with both the current ros_buildfarm release and master with xenial.

**Comment by dirk-thomas** [comment]
> I think we can merge this now but I want to confirm with you.

:+1:

**Comment by nuclearsandwich** [comment]
Thanks @tonybaltovski 🥇

**Pull request merged**
