### PR TITLE
disable rosjava_boostrap on jessie due to SSL issues

### PR DESCRIPTION
**Pull request by tfoote**
https://github.com/rosjava/rosjava_bootstrap/issues/61

http://build.ros.org/view/Kbin_dj_dJ64/job/Kbin_dj_dJ64__rosjava_bootstrap__debian_jessie_amd64__binary/
http://build.ros.org/view/Kbin_dj_dJ64/job/Kbin_djv8_dJv8__rosjava_bootstrap__debian_jessie_arm64__binary/

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
it looks like this failure is present on all arm builds and not only debian Jessie
http://build.ros.org/view/Kbin_uxv8_uXv8/job/Kbin_uxv8_uXv8__rosjava_bootstrap__ubuntu_xenial_arm64__binary/430/console
http://build.ros.org/view/Kbin_uxhf_uXhf/job/Kbin_uxhf_uXhf__rosjava_bootstrap__ubuntu_xenial_armhf__binary/351/console

**Comment by tfoote** [comment]
True, it's not flagged as a regression, because I believe that they have never worked. I guess we should disable on the other arm platforms too. This package has always had trouble but was recently added as a dependency which is causing the regressions. 

@ernestmc  @jubeira I'm going to add the other arm platforms to the blacklist too.

**Review by mikaelarguedas — APPROVED** [review]
lgtm

**Comment by mikaelarguedas** [comment]
> True, it's not flagged as a regression, because I believe that they have never worked.

Yeah I see a few rosjava packages in indigo that seem to have been failing on arm forever as well and would deserve the same treatment
http://repositories.ros.org/status_page/ros_indigo_arm.html?q=rosjava

**Comment by tfoote** [comment]
They're already disabled. Unfortunately the status page doesn't know about blacklisting. It only knows they they're missing in the repo.

**Pull request merged**
