### PR TITLE
add list_priorities script

### PR DESCRIPTION
**Pull request by dirk-thomas**
Summarizes the priorities used across all build files. For example output see https://github.com/ros-infrastructure/ros_buildfarm_config/pull/25#issuecomment-190439364

### CODE REVIEW

**Comment by esteve** [comment]
+1

**Comment by tfoote** [comment]
please cherry pick this to master too

**Comment by dirk-thomas** [comment]
576a482f953e0af44c0e66edf145dc329579da69

**Comment by dirk-thomas** [comment]
576a482f953e0af44c0e66edf145dc329579da69

**Pull request merged**
