### PR TITLE
Noetic blacklist cob_monitoring

### PR DESCRIPTION
**Pull request by sloretz**
https://answers.ros.org/question/366881/
https://github.com/ipa320/cob_command_tools/issues/289

Signed-off-by: Shane Loretz <sloretz@openrobotics.org>
Signed-off-by: Shane Loretz <sloretz@osrfoundation.org>

@fmessmer FYI this will stop the cob_monitorying buildfarm jobs for Noetic

### CODE REVIEW

**Comment by fmessmer** [comment]
great, thanks!

just one more question:
what about the downstream dependencies?
e.g. the cob_command_tools meta-package or other packages declaring a dependency on cob_monitoring?
do they need to get blacklisted, too?

I'm also getting similar mails for other cob_command_tools packages although only cob_monitoring has an unmet dependency on buster (as far as i can tell)
does this fix the build failure also for those jobs?

**Comment by cottsay** [comment]
> what about the downstream dependencies?

Any package which depends on an excluded package will also be excluded, so you should see those jobs get disabled as well.

**Review by cottsay — APPROVED** [review]

**Comment by fmessmer** [comment]
thanks for clarifying!

**Comment by fmessmer** [comment]
I still have issues with failure reports for other packages from the same `cob_command_tools` repository
I posted a follow-up question:  https://answers.ros.org/question/366881/noetic-build-failed-in-jenkins-debianbuster-could-not-resolve-rosdep-key/?answer=367253#post-id-367253

**Pull request merged**
